<a href="https://colab.research.google.com/github/Dahlia-Chehata/Data-Mining/blob/master/Lab%204/Data_Mining_sheet_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Question 3-3-a**

Same solution as the previous question 3-2

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import Ridge
x1 = [1,2,2,2,3,3,4,4,4,5]
x2 = [5,6,10,12,17,12,6,5,7,10]
y = [10,40,50,60,70,50,30,20,40,70]
X = [x1, x2]
reg = linear_model.LinearRegression()
reg.fit(np.array(X).transpose(), y)
coeffs = reg.coef_
a = reg.intercept_
print("Estimated coefficients: ( coeffs[0] = " ,coeffs[0] , "   coeffs[1] = " , coeffs[1] , "  ) " ) 
print("Intercept = " , a)

Estimated coefficients: ( coeffs[0] =  4.285714285714283    coeffs[1] =  4.3478260869565215   ) 
Intercept =  -7.987577639751542


**Question 3-3-b**



In [40]:
alpha = [0.1,1,10,100]
equation = ["" for x in range(4)]
for i in range(len(alpha)):
  clf = Ridge(alpha[i])
  clf.fit(np.array(X).transpose(), y)
  b = clf.coef_
  c = clf.intercept_
  print("alpha = ",alpha[i])
  print("Estimated coefficients: ( coeffs[0] = " ,b[0] , "   coeffs[1] = " , b[1] , "  ) " ) 
  print("Intercept =  " , c)
  equation [i]='{0}*x1+{1}*x2+({2})'.format(b[0],b[1], c)
  print("equation :"+ equation[i])


alpha =  0.1
Estimated coefficients: ( coeffs[0] =  4.25531914893617    coeffs[1] =  4.34467776973208   ) 
Intercept =   -7.868057374397225
equation :4.25531914893617*x1+4.34467776973208*x2+(-7.868057374397225)
alpha =  1
Estimated coefficients: ( coeffs[0] =  3.999999999999999    coeffs[1] =  4.316546762589928   ) 
Intercept =   -6.8489208633093455
equation :3.999999999999999*x1+4.316546762589928*x2+(-6.8489208633093455)
alpha =  10
Estimated coefficients: ( coeffs[0] =  2.500000000000001    coeffs[1] =  4.054054054054054   ) 
Intercept =   0.013513513513508713
equation :2.500000000000001*x1+4.054054054054054*x2+(0.013513513513508713)
alpha =  100
Estimated coefficients: ( coeffs[0] =  0.5263157894736843    coeffs[1] =  2.5210084033613445   ) 
Intercept =   19.73197700132685
equation :0.5263157894736843*x1+2.5210084033613445*x2+(19.73197700132685)


**Question 3-4  : 
**
**Solved using 2 approaches:  **
1.    perdict the values directly from the model
2.     use the computed coefficients and intercept and substitute                                                        in equations



**Approach 1**

In [14]:
p1 = [3,16]
p2 = [2,4]
p3 = [5,4]
P = [p1, p2, p3]
print("p1, p2, p3 with linear regression = ")
print(reg.predict(P))
alpha = [0.1,1,10,100]
for i in range(len(alpha)):
  clf = Ridge(alpha[i])
  clf.fit(np.array(X).transpose(), y)
  print("p1, p2, p3 after L-2 regularization at alpha = ",alpha[i])
  print(clf.predict(P))

p1, p2, p3 with linear regression = 
[74.43478261 17.97515528 30.83229814]
p1, p2, p3 after L-2 regularization at alpha =  0.1
[74.41274439 18.021292   30.78724945]
p1, p2, p3 after L-2 regularization at alpha =  1
[74.21582734 18.41726619 30.41726619]
p1, p2, p3 after L-2 regularization at alpha =  10
[72.37837838 21.22972973 28.72972973]
p1, p2, p3 after L-2 regularization at alpha =  100
[61.64705882 30.86864219 32.44758956]


**Approach 2**


In [55]:
import sympy

equation.append('{0}*x1+{1}*x2+({2})'.format(coeffs[0],coeffs[1], reg.intercept_))

def eval_eqn(eqn,in_dict):
    subs = {sympy.symbols(key):item for key,item in in_dict.items()}
    ans = sympy.simplify(eqn).evalf(subs = subs)

    return ans
def print_dict (dict): 
  print ("point :")
  for keys,values in dict.items():
    print(keys, " = ",values)
  
in_dict = ["" for x in range(3)]  
  
in_dict[0] = {"x1":3,"x2":16}
in_dict[1] = {"x1":2,"x2":4}
in_dict[2] = {"x1":5,"x2":4}


for i in range (len(equation)):
  print ( "equation : y = "+ equation[i])
  for j in range (len(in_dict)):
    print_dict(in_dict[j])
    print(eval_eqn(equation[i],in_dict[j]))

  

equation : y = 4.25531914893617*x1+4.34467776973208*x2+(-7.868057374397225)
point :
x1  =  3
x2  =  16
74.4127443881246
point :
x1  =  2
x2  =  4
18.0212920024034
point :
x1  =  5
x2  =  4
30.7872494492119
equation : y = 3.999999999999999*x1+4.316546762589928*x2+(-6.8489208633093455)
point :
x1  =  3
x2  =  16
74.2158273381295
point :
x1  =  2
x2  =  4
18.4172661870504
point :
x1  =  5
x2  =  4
30.4172661870504
equation : y = 2.500000000000001*x1+4.054054054054054*x2+(0.013513513513508713)
point :
x1  =  3
x2  =  16
72.3783783783784
point :
x1  =  2
x2  =  4
21.2297297297297
point :
x1  =  5
x2  =  4
28.7297297297297
equation : y = 0.5263157894736843*x1+2.5210084033613445*x2+(19.73197700132685)
point :
x1  =  3
x2  =  16
61.6470588235294
point :
x1  =  2
x2  =  4
30.8686421937196
point :
x1  =  5
x2  =  4
32.4475895621406
equation : y = 4.285714285714283*x1+4.3478260869565215*x2+(-7.987577639751542)
point :
x1  =  3
x2  =  16
74.4347826086957
point :
x1  =  2
x2  =  4
17.9751552795031
